# TODO: Finish this! currently untested

AWSTemplateFormatVersion: 2010-09-09
Description: Set up Dupin in EC2 and schedule its execution

Parameters:
  AMI:
    Description: AMI for the underlying instance
    Type: AWS::EC2::Image::Id
  VpcId:
    Description: The VPC in which Dupin will run
    Type: AWS::EC2::VPC::Id
  Subnet:
    Description: The subnets where the instance can run
    Type: AWS::EC2::Subnet::Id
  KeyName:
    Description: An ssh keypair to put on the nginx instance
    Type: AWS::EC2::KeyPair::KeyName
  SSHAccessCidr:
    Description: A CIDR from which SSH access to the nginx instance is allowed
    Type: String
    AllowedPattern: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/[0-9]{1,2}$
    ConstraintDescription: Parameter should be a CIDR block e.g. "1.2.3.4/32"

Mappings:
  Tags:
    App:
      Value: dupin
    Stack:
      Value: security

Resources:
  DupinInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Dupin instance security group
      VpcId:
        Ref: VpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp:
          Ref: SSHAccessCidr
      SecurityGroupEgress:
      # allow instance to make http requests for init
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
      Tags:
      - Key: App
        Value: !FindInMap [ Tags, App, Value ]
      - Key: Stack
        Value: !FindInMap [ Tags, Stack, Value ]

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
      - Ref: InstanceRole

  DupinInstance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              git: []
              python-pip: []
          files:
            /etc/cron.d/discover-loadupstream-instances:
              # scan org's repos on a daily basis at 14:30
              mode: "000644"
              owner: root
              group: root
              content: !Sub |
                30 14 * * *  ec2-user  bash dupin auto-scan-all --root /dupin --notify
            /etc/cron.d/dupin-update-org-repos:
              # updates the organisation's repositories every Monday at 09:00
              mode: "000644"
              owner: root
              group: root
              content: !Sub |
                0 9 * * 1  ec2-user  bash dupin update-repos --root /dupin
    Properties:
      ImageId:
        Ref: AMI
      InstanceType: t2.nano
      KeyName:
        Ref: KeyName
      IamInstanceProfile:
        Ref: InstanceProfile
      NetworkInterfaces:
      - DeviceIndex: 0
        AssociatePublicIpAddress: true
        SubnetId:
          Ref: Subnet
        GroupSet:
        - Ref: DupinInstanceSecurityGroup
      Tags:
      - Key: Name
        Value: !FindInMap [ Tags, App, Value ]
      - Key: App
        Value: !FindInMap [ Tags, App, Value ]
      - Key: Stack
        Value: !FindInMap [ Tags, Stack, Value ]
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -ev
          yum update -y
          yum install -y aws-cfn-bootstrap

          /opt/aws/bin/cfn-init -v \
                   --stack ${AWS::StackName} \
                   --resource DupinInstance \
                   --region ${AWS::Region}

          pip install --upgrade pip

          # setup dupin directories
          mkdir /dupin

          # fetch dupin
          git clone git@github.com:guardian/dupin.git /dupin/dupin-src

          # install dupin and requirements
          pip install /dupin/dupin-src

          # fetch config
          aws s3 cp !!TODO!! /dupin/config

          chown -R ec2-user /dupin

          # run dupin setup
          su -c "dupin --root /dupin setup" ec2-user

          # update organisation repos
          su -c "dupin --root /dupin update-repos" ec2-user

          # enable automatic patching
          /sbin/chkconfig --level 345 yum on; /sbin/service yum start

Outputs:
  DupinInstanceIP:
    Value:
      !GetAtt DupinInstance.PublicDnsName
